// Segmento: Admissão
{ title: "Agente de Admissão", linhaProduto: "HCM", segmento: "Admissão", description: "Orienta candidatos aprovados no processo seletivo, fornecendo informações sobre documentação necessária, integração e primeiros passos na empresa.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Modelos de convite por SMS", linhaProduto: "HCM", segmento: "Admissão", description: "Gera texto vase para envio de convite de admissão a novos colaboradores", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Modelo do convite", linhaProduto: "HCM", segmento: "Admissão", description: "Gera texto base para o modelo de convite para envio aos candidatos", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Texto com instruções para o assinante", linhaProduto: "HCM", segmento: "Admissão", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Criar conteúdo dos documentos admissionais", linhaProduto: "HCM", segmento: "Admissão", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
// Segmento: Agronegócio
{ title: "Agente de Qualidade da Colheita", linhaProduto: "ERP", segmento: "Agronegócio", description: "Monitora e avalia a qualidade das colheitas, garantindo que os padrões estabelecidos sejam atendidos.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Qualidade das Commodities", linhaProduto: "ERP", segmento: "Agronegócio", description: "Assegura que os produtos agrícolas atendam aos critérios de qualidade para comercialização.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Performance Operacional", linhaProduto: "ERP", segmento: "Agronegócio", description: "Avalia o desempenho das operações agrícolas, identificando áreas para otimização e melhoria.", contexto: "Execução e operação", tags: ["Roadmap"] },
// Segmento: Backoffice
{ title: "Abordagem de Venda", linhaProduto: "ERP", segmento: "Backoffice", description: "Elaboração de e-mail para prospect com IA", contexto: "nan", tags: ["Liberado"] },
{ title: "Gerador de conteúdo - E-mail Marketing", linhaProduto: "ERP", segmento: "Backoffice", description: "Elaboração de campanha de e-mail mkt com IA", contexto: "nan", tags: ["Liberado"] },
{ title: "Requisição  de Estoque", linhaProduto: "ERP", segmento: "Backoffice", description: "Complemento e descrição de itens da requisição de estoque ", contexto: "nan", tags: ["Liberado"] },
{ title: "Sales", linhaProduto: "ERP", segmento: "Backoffice", description: "Assistência a interpretação e consumo dos dados de vendas do ERP", contexto: "nan", tags: ["Roadmap"] },
{ title: "Invoicing", linhaProduto: "ERP", segmento: "Backoffice", description: "Assistência a interpretação e consumo dos dados de faturamento do ERP", contexto: "nan", tags: ["Roadmap"] },
{ title: "Expert Suprimentos", linhaProduto: "ERP", segmento: "Backoffice", description: "Assistência a interpretação e consumo dos dados de suprimentos do ERP", contexto: "nan", tags: ["Roadmap"] },
{ title: "Virtual CFO", linhaProduto: "ERP", segmento: "Backoffice", description: "Assistência a interpretação e consumo dos dados financeiros do fluxo de caixa", contexto: "nan", tags: ["Roadmap"] },
{ title: "Resumo de Negociação", linhaProduto: "ERP", segmento: "Backoffice", description: "Síntese das negociações para personas de gestão", contexto: "nan", tags: ["Roadmap"] },
{ title: "Insights Faturamento", linhaProduto: "ERP", segmento: "Backoffice", description: "Variação de faturamento nos ultimos dois meses | Analise de faturamento ultimo mês | Analise de desempenho mensal nos ultimos doze meses", contexto: "nan", tags: ["Liberado"] },
{ title: "Insight prazos financeiros", linhaProduto: "ERP", segmento: "Backoffice", description: "Calculo do ciclo financeiro com PMR, PMP e compras", contexto: "nan", tags: ["Liberado"] },
{ title: "Insight de cobrança", linhaProduto: "ERP", segmento: "Backoffice", description: "Elaboração de e-mail de cobrança com base na seleção de tiulos diretamente na tela de consulta do ERP", contexto: "nan", tags: ["Liberado"] },
{ title: "Insights Vendas", linhaProduto: "ERP", segmento: "Backoffice", description: "Variação do ticket medio nos ultimos dois meses | Analise de faturamento, ticket medio) no ultimo mês | Indicadores de desempenho mensal nos ultimos doze meses", contexto: "nan", tags: ["Liberado"] },
{ title: "Insights Estoques", linhaProduto: "ERP", segmento: "Backoffice", description: "Produtos com saldo em estoque abaixo do mínimo | Estoque de maior valor | Recomendações para prevenção de rupturas", contexto: "nan", tags: ["Liberado"] },
{ title: "Insights Recebimentos", linhaProduto: "ERP", segmento: "Backoffice", description: "Melhores oportunidades de crédito de imposto | Análise do valor de compras mensais", contexto: "nan", tags: ["Liberado"] },
{ title: "Insights Faturamento", linhaProduto: "ERP", segmento: "Backoffice", description: "Ag confirmação dos insights", contexto: "nan", tags: ["Roadmap"] },
{ title: "Insights Compras", linhaProduto: "ERP", segmento: "Backoffice", description: "nan", contexto: "nan", tags: ["Roadmap"] },
{ title: "Insights Financeiros", linhaProduto: "ERP", segmento: "Backoffice", description: "nan", contexto: "nan", tags: ["Roadmap"] },
{ title: "Insights Mercado", linhaProduto: "ERP", segmento: "Backoffice", description: "nan", contexto: "nan", tags: ["Roadmap"] },
{ title: "Predição de Faturamento", linhaProduto: "ERP", segmento: "Backoffice", description: "Estimativa de faturamento bruto por CNPJ", contexto: "nan", tags: ["Liberado"] },
{ title: "Predição de número de Funcionários", linhaProduto: "ERP", segmento: "Backoffice", description: "Estimativa de numero de empregados de CNPJ", contexto: "nan", tags: ["Liberado"] },
{ title: "Insight Negociações", linhaProduto: "ERP", segmento: "Backoffice", description: "Assistente de vendas - apoio à equipe de vendas para encontrar as melhores sugestões para realização da venda", contexto: "Liderança estratégica", tags: ["Roadmap"] },
// Segmento: Compliance
{ title: "TAX", linhaProduto: "ERP", segmento: "Compliance", description: "Assistência a interpretação e consumo dos dados tributários da oferta Simulador X (Reforma)", contexto: "nan", tags: ["Roadmap"] },
{ title: "Insights Contabilidade", linhaProduto: "ERP", segmento: "Compliance", description: "Prazo médio (em dias) de recebimento, pagamento e estoques | Saude financeira da empresa | Redução de custos da empresa", contexto: "nan", tags: ["Liberado"] },
{ title: "Insights Contábil", linhaProduto: "ERP", segmento: "Compliance", description: "nan", contexto: "nan", tags: ["Roadmap"] },
{ title: "Insights Fiscais", linhaProduto: "ERP", segmento: "Compliance", description: "nan", contexto: "nan", tags: ["Roadmap"] },
{ title: "Analista de suporte Sara", linhaProduto: "ERP", segmento: "Compliance", description: "Sara especialista de suporte nas mensagens de erro de envio de documentos. A IA embarcada consome dados dos KCS de suporte pra direcionar à solução do problema", contexto: "nan", tags: ["Roadmap"] },
{ title: "Recebimento de NFS-e via PDF", linhaProduto: "ERP", segmento: "Compliance", description: "Leitura de documentos padrões para lançamento automático no sistema", contexto: "nan", tags: ["Roadmap"] },
// Segmento: Compras
{ title: "Agente de Performance de Compras", linhaProduto: "ERP", segmento: "Compras", description: "Avalia o desempenho do setor de compras, buscando eficiência e redução de custos.", contexto: "Execução e operação", tags: ["Roadmap"] },
// Segmento: Construção
{ title: "Agente de Orçamento", linhaProduto: "ERP", segmento: "Construção", description: "Elabora e monitora os orçamentos dos projetos, assegurando aderência aos custos previstos.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Planejamento", linhaProduto: "ERP", segmento: "Construção", description: "Define cronogramas e etapas dos projetos, coordenando recursos e prazos.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Receitas", linhaProduto: "ERP", segmento: "Construção", description: "Acompanha as entradas financeiras dos projetos, garantindo a saúde financeira dos empreendimentos.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Solicitações", linhaProduto: "ERP", segmento: "Construção", description: "Gerencia pedidos e requisições relacionadas aos projetos, assegurando respostas ágeis e adequadas.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Otimização de Compras", linhaProduto: "ERP", segmento: "Construção", description: "Busca as melhores condições de aquisição de materiais e serviços, visando economia e qualidade.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Distratos", linhaProduto: "ERP", segmento: "Construção", description: "Administra cancelamentos de contratos, garantindo o cumprimento de cláusulas.", contexto: "Execução e operação", tags: ["Roadmap"] },
// Segmento: Desempenho
{ title: "Agente de Avaliação de Desempenho", linhaProduto: "HCM", segmento: "Desempenho", description: "Auxilia na avaliação periódica dos colaboradores, fornecendo insights sobre desempenho e áreas de melhoria.", contexto: "Liderança estratégica", tags: ["Roadmap"] },
{ title: "Agente de PDIs (Planos de Desenvolvimento Individual)", linhaProduto: "HCM", segmento: "Desempenho", description: "Ajuda na criação e monitoramento de planos personalizados para o desenvolvimento profissional dos membros da equipe.", contexto: "Liderança estratégica", tags: ["Roadmap"] },
{ title: "Agente de Feedbacks", linhaProduto: "HCM", segmento: "Desempenho", description: "Facilita a coleta e gestão de feedbacks contínuos entre líderes e colaboradores.", contexto: "Liderança estratégica", tags: ["Roadmap"] },
{ title: "Agente 1:1 (Reuniões Individuais)", linhaProduto: "HCM", segmento: "Desempenho", description: "Organiza e sugere pautas para reuniões individuais entre líderes e membros da equipe.", contexto: "Liderança estratégica", tags: ["Roadmap"] },
{ title: "Geração de PDI", linhaProduto: "HCM", segmento: "Desempenho", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Evidências das competências", linhaProduto: "HCM", segmento: "Desempenho", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Criação de meta da avaliação de resultados", linhaProduto: "HCM", segmento: "Desempenho", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
// Segmento: Diversidade e inclusão
{ title: "Insights de Diversidade", linhaProduto: "HCM", segmento: "Diversidade e inclusão", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
// Segmento: Estoque
{ title: "Agente de Estoque", linhaProduto: "ERP", segmento: "Estoque", description: "Gerencia os níveis de estoque, evitando excessos ou faltas de produtos.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Alocação de Estoque", linhaProduto: "ERP", segmento: "Estoque", description: "Determina a distribuição ideal dos produtos em estoque para atender à demanda.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Inventário", linhaProduto: "ERP", segmento: "Estoque", description: "Realiza auditorias e controle dos itens em estoque, assegurando a precisão dos registros.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Controle de Pátio", linhaProduto: "ERP", segmento: "Estoque", description: "Organiza e monitora as atividades no pátio industrial, garantindo fluxo eficiente de materiais e produtos.", contexto: "Execução e operação", tags: ["Roadmap"] },
// Segmento: Financeiro
{ title: "Agente de Contas a Receber", linhaProduto: "ERP", segmento: "Financeiro", description: "Gerencia entradas financeiras, acompanhando pagamentos e identificando inadimplências.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Contas a Pagar", linhaProduto: "ERP", segmento: "Financeiro", description: "Supervisiona as obrigações financeiras da empresa, garantindo pagamentos em dia e controle de despesas.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Tesouraria", linhaProduto: "ERP", segmento: "Financeiro", description: "Controla o fluxo de caixa, assegurando a liquidez necessária para as operações diárias.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente Fiscal", linhaProduto: "ERP", segmento: "Financeiro", description: "Garante a conformidade com as obrigações fiscais, monitorando prazos e regulamentos tributários.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente Contábil", linhaProduto: "ERP", segmento: "Financeiro", description: "Mantém os registros contábeis atualizados, facilitando a elaboração de demonstrações financeiras precisas.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Faturamento", linhaProduto: "ERP", segmento: "Financeiro", description: "Emite e gerencia faturas, assegurando a correta cobrança pelos serviços ou produtos fornecidos.", contexto: "Execução e operação", tags: ["Roadmap"] },
// Segmento: Gestão do ponto
{ title: "Insight - Marcações de ponto em cada modo", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações de ponto online e offline", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações em cada plataforma", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações em dispositivos sem permissão para usar a câmera", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações registradas fora, dentro ou sem a cerca virtual", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações com ou sem permissão de localização", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações com reconhecimento", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações com reconhecimento facial cadastrado ou cancelado", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações com foto não permitida, foto cancelada ou sem permissão para usar a câmera", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações com captura de foto cancelada pelo usuário", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações realizadas com assinatura inválida ou válida", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações realizadas no modo Múltiplo", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações realizadas no modo Individual", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações realizadas no modo Motorista", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações realizadas no modo QR Code", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações realizadas no modo NFC", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações realizadas no modo Biometria", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Insight - Marcações realizadas no modo Reconhecimento Facial", linhaProduto: "HCM", segmento: "Gestão do ponto", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
// Segmento: Indústria
{ title: "Agente de Gestão da Produção", linhaProduto: "ERP", segmento: "Indústria", description: "Supervisiona o processo produtivo, garantindo eficiência e cumprimento dos cronogramas.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Planejamento e Controle da Produção", linhaProduto: "ERP", segmento: "Indústria", description: "Planeja as atividades produtivas, otimizando recursos e tempos de produção.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Custos", linhaProduto: "ERP", segmento: "Indústria", description: "Monitora os custos operacionais, identificando oportunidades de economia.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Manufacturing", linhaProduto: "ERP", segmento: "Indústria", description: "Assistência a interpretação e consumo dos dados de industrialização do ERP", contexto: "nan", tags: ["Roadmap"] },
{ title: "Insights Custos", linhaProduto: "ERP", segmento: "Indústria", description: "Análise dos dados de fechamento de custos do periodo em tela de produto", contexto: "nan", tags: ["Roadmap"] },
{ title: "Insights Industrial", linhaProduto: "ERP", segmento: "Indústria", description: "Eficácia de estágios/recursos (tempo, refugo, parada)", contexto: "nan", tags: ["Roadmap"] },
{ title: "Insights Produção", linhaProduto: "ERP", segmento: "Indústria", description: "nan", contexto: "nan", tags: ["Roadmap"] },
{ title: "CRP", linhaProduto: "ERP", segmento: "Indústria", description: "Otimização de linha de produção", contexto: "nan", tags: ["Roadmap"] },
// Segmento: Painel de gestão
{ title: "Justificativa na avaliação contratual", linhaProduto: "HCM", segmento: "Painel de gestão", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Escrever feedback", linhaProduto: "HCM", segmento: "Painel de gestão", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Resumo de perfil profissional", linhaProduto: "HCM", segmento: "Painel de gestão", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
// Segmento: Portal de talentos
{ title: "Descrever sobre você", linhaProduto: "HCM", segmento: "Portal de talentos", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
// Segmento: Recrutamento e seleção
{ title: "Agente Recrutador", linhaProduto: "HCM", segmento: "Recrutamento e seleção", description: "Apoia os analistas de recrutamento e seleção na triagem de candidatos, agendamento de entrevistas e comunicação com potenciais colaboradores.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Descrição da Vaga", linhaProduto: "HCM", segmento: "Recrutamento e seleção", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Geração de mensagens ao candidato", linhaProduto: "HCM", segmento: "Recrutamento e seleção", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Descrição do "perfil" na requisição de pessoal", linhaProduto: "HCM", segmento: "Recrutamento e seleção", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
// Segmento: Remuneração
{ title: "Descrição de Cargos", linhaProduto: "HCM", segmento: "Remuneração", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Sugestão de justificativa de transferência", linhaProduto: "HCM", segmento: "Remuneração", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
{ title: "Sugestão de justificativa de proposta", linhaProduto: "HCM", segmento: "Remuneração", description: "nan", contexto: "Execução e operação", tags: ["nan"] },
// Segmento: Transporte
{ title: "Agente de Expedição", linhaProduto: "Logística", segmento: "Transporte", description: "Coordena o envio de produtos aos clientes, assegurando prazos e condições adequadas de transporte.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Recebimento", linhaProduto: "Logística", segmento: "Transporte", description: "Supervisiona a entrada de materiais e produtos, conferindo quantidades e qualidade.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Rotas", linhaProduto: "Logística", segmento: "Transporte", description: "Otimize as rotas de entrega e coleta, buscando eficiência logística.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Frotas:", linhaProduto: "Logística", segmento: "Transporte", description: "Gerencia os veículos da empresa, programando manutenções e controlando custos operacionais.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Fretes", linhaProduto: "Logística", segmento: "Transporte", description: "Negocia e controla os custos de transporte, buscando parcerias vantajosas.", contexto: "Execução e operação", tags: ["Roadmap"] },
{ title: "Agente de Entregas", linhaProduto: "Logística", segmento: "Transporte", description: "Acompanha o status das entregas, garantindo a satisfação dos clientes.", contexto: "Execução e operação", tags: ["Roadmap"] },
// Segmento: Waapi - Mobilidade
{ title: "Escrever feedback", linhaProduto: "HCM", segmento: "Waapi - Mobilidade", description: "nan", contexto: "Execução e operação", tags: ["nan"] },